"""empty message

Revision ID: 4635ffeca26b
Revises: 5082b98342d3
Create Date: 2018-03-09 22:15:58.233547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4635ffeca26b'
down_revision = '5082b98342d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('location', sa.String(length=80), nullable=True))
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'age')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    op.drop_column('user_profile', 'location')
    op.drop_column('user_profile', 'email')
    # ### end Alembic commands ###
